### ISSUE TITLE
Any plans for Teams channel exports?

### ISSUE THREAD

**Issue by altugozcelikkale** [evenevan/export-ms-teams-chats#5]
Thank you for your hard work with this script. Our university is transitioning to a different Microsoft service plan and recommended us to backup/export our data. Using your script and instructions, I managed to export all my Teams individual and grup chats into neatly organized html files with all the text and images, which is awesome!

Is there any way the script can be extended to include html export of posts in _public and private channels in Teams_ that are administered by the authorized user? If so that would be a great addition. This is the only functionality that is missing which would allow me migrate away from Teams with a decent log of our 4+ years old history of team discussions.

Thanks!

**Comment by attituding** [comment]
Hey! Glad to hear the script works in some capacity for you.

Adding support for exporting stuff in teams channels seems very much possible, but appears to require significant effort to accomplish. I have no plans to work on that at the moment owing to limited availability. If I had to make a guess on when work on such functionality may or may not start, it would be no earlier than mid August.

**Comment by mriveratel** [comment]
The work done is impressive and fills an important gap that the Teams client should have natively, thank you very much for your contribution.

Regarding the export of channel chats, for me it is very important because before deleting a channel we need to export all the conversations to save them as proof of what was agreed in the channel. I use Teams channels to replace the use of email, which I can save as proof of what was agreed.

It would be very useful to have a similar script to export Teams channels that could be run by channel owners.

I will keep an eye on the conversation, thank you.

**Comment by mriveratel** [comment]
Hi evenevan, 
Have you already decided whether you are going to implement this interesting feature? I am sure it will be very useful for many other Teams users. Thank you.

**Comment by evenevan** [comment]
Hey!

Unfortunately, at this time, I lack the bandwidth to make this addition.

I know how much value such feature would add, so I definitely still have it on my radar.

Its possible that one of the forks of this project have added this feature, so you may want to have a quick look to see if anyone has. Otherwise, if you know (or are) someone that might be able to help implement this feature, contributions are very welcome.

**Comment by mriveratel** [comment]
Hi!

I followed your instructions to check the forks (I saw that there are 6) and I didn't see any in this regard. The first time I went to GitHub was to see this functionality, so it's possible that I missed something.

I would like to collaborate, but I don't have the programming knowledge for this development. I did something many years ago, but I'm very outdated. I can understand part of the code with effort, but I couldn't provide a solution.

Thanks for the answer. I'll keep an eye out for any changes.

**Comment by evenevan** [comment]
While I cannot specifically endorse this as I have not tried it nor looked into it with particular detail, it seems https://github.com/Staas-0/TeamsDumper may be an implementation of what you are looking for. It looks like you'll need to create your own Azure app and stuff but if you can do that, that'll maybe work.
