### ISSUE TITLE
Alternative way of signing in

### ISSUE THREAD

**Issue by NightMean** [evenevan/export-ms-teams-chats#9]
Hi, I just tried to use this tool but when I tried to sign in on the web, I was prompted with an message saying that I don't have access to this as admin has restricted this authentication method via some policy. 

Unfortunately, I'm not able to reach the admin to allow this type of auth. |
Is there any other way I could sign to this tool? Maybe by providing cookies from browser, etc. 

![image](https://github.com/user-attachments/assets/c33ee5b5-2489-4c98-815e-d629dc5882a4)

Edit: I just noticed this in Readme
`If you run into issues with authentication, specifically with permissions requiring admin consent, there is not much I can do.`

**Comment by evenevan** [comment]
This is a bit different than the permissions requested by the app being admin restricted; there might or might not be a way around this. It seems devicelogin, if not also other auth methods, are disallowed. Rather than devicelogin, it is possible that authentication with the `https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize` endpoint would work assuming your admin hasn't disabled that also. Unfortunately I lack the time to try implementing this. If you are someone else would be interested in looking more into this, see https://learn.microsoft.com/en-us/graph/auth-v2-user?tabs=http. Apologies I don't have a more solid solution.
